### ISSUE TITLE
Get stream data

### ISSUE THREAD

**Issue by marcelaraujo** [jiangmiao/node-curl#11]
How can I get the stream data if callback is only called after connection ended?

Thanks

**Comment by jiangmiao** [comment]
Currently there is no public way to do that only a hack way, rewrite curl.curl_'s behavior.

```
curl.setOptions({
  URL: 'www.yahoo.com'
});

curl_ = curl.curl_;

curl_.on_write = function(chunk) {
  console.info(chunk.length);
  // return 0 will cause curl_ terminated in future.
  return chunk.length;
};

curl_.on_error = function(err) {
  return console.info(err);
};

curl_.on_end = function() {
  console.info('done.');
  console.info('status:', this.getinfo('RESPONSE_CODE'));
  return console.info('effective url:', this.getinfo('EFFECTIVE_URL'));
};

curl_.perform();
```

and there is a issue, the perform() cannot be stopped by manual. the future design is on_write return 0 will cause curl_ terminated.

**Comment by marcelaraujo** [comment]
Tks

**Comment by jValdron** [comment]
Just wanted to add my two cents. I had problems when I tried to download more than one file at the same time. I had to call curl.open() to make it work properly, like so:

``` javascript

// Include the required library.
var curl = require('node-curl');

// Open up a new CURL instance.
curl.open();

// Set the URL option.
curl.setOptions({
    URL: req.body.file
});

// ... etc

```

**Comment by jiangmiao** [comment]
It seems you are using node-curl in wrong way. The code should be

```
var curl = require('node-curl');

curl(req.body.file, function(e) {
    console.log(this.body);
});
```

If download more than one file in parallel use `curl.create()` to create another curl session.

**Comment by jValdron** [comment]
Well, I'm overriding the default behavior like explained in this thread. I'm streaming the files, using the buffer to do manipulation, then uploading to S3 without storing anything on disk.

**Comment by jiangmiao** [comment]
curl should be opened before setOptions.
after opening, it will not close until user call `curl.close()` or process exit.
also you could add line `curl.debug = true`  to see the debug log.

**Comment by jValdron** [comment]
Alright, I've updated my code a little bit, it looks something like that:

``` javascript

// Include the required library.
var curl = require('node-curl');

// Create a new CURL instance.
curl = curl.create();

// Open up CURL.
curl.open();

// Set the URL option.
curl.setOptions({
    URL: req.body.file
});

// And closing CURL it in curl.curl_.on_end.

```

This works way better now!

**Comment by jiangmiao** [comment]
In default behaviour the create() contains curl.open() 
and require('node-curl') is created by create().
curl.curl_ is created when the curl.open() called.
curl.curl_ will be set to null when curl.close() called. and any reference of curl.curl_ will be invalid.

**Comment by jValdron** [comment]
Alright, thanks for this information. It will help me understand a little
bit more how it works on in the inside.

**Comment by jiangmiao** [comment]
I've add a low-level Curl and publish it in 0.2.0, you can use it to write the stream easier.
Example:

``` javascript
var Curl = require('node-curl/lib/Curl')

var p = console.log;
var url = process.argv[2];

var curl = new Curl();

if (!url)
    url = 'www.yahoo.com';

curl.setopt('URL', url);
curl.setopt('CONNECTTIMEOUT', 2);

// on 'data' must be returns chunk.length, or means interrupt the transfer
curl.on('data', function(chunk) {
    p("receive " + chunk.length)
    return chunk.length;
});

curl.on('error', function(e) {
    p("error: " + e.message)
    curl.close();
});


curl.on('end', function() {
    p('done.')
    curl.close();
});

curl.perform();
```

**Comment by jValdron** [comment]
Thanks! I did manage to make it work properly yesterday using the hack.

However, using 0.2.0, I can't seem to be able to call `var curl = new Curl();` without any arguments. I'm getting "Cannot set option URL to undefined". So I assume I need to pass the URL to `new Curl(url)`. Doing so however, in CurlBuilder, it assumes that since I only have one argument, it's the callback (line 48, `cb = args.pop()`).

And when I pass `new Curl(url, function(){})`, it gives me: "The curl session is running, use curl.create() to create another session."

Also, version 0.2.0 broke my previous code that used `curl.curl_.on_write`, etc.

**Comment by jiangmiao** [comment]
It seems the you've require wrong file.
the `node-curl/lib/Curl` is difference from `node-curl`, require('node-curl') returns a function/object mixed thing by lib/CurlBuilder.create(), which is wrapped node-curl/lib/Curl.

**Comment by jValdron** [comment]
Makes sense. However, I'm now getting a segmentation fault.

Here's my code:

``` javascript

// Include the required library.
var curl = require('node-curl/lib/Curl');

// Create a new CURL instance.
var request = new curl();

// Set the URL for CURL.
request.setopt('URL', req.body.file);

// Get chunks of data.
request.on('data', function(chunk){

    // Some progress calculating and stuff here ...

    append(chunk);

});

// When the request is done, we should close CURL.
request.on('end', function(){

    // Close CURL.
    curl.close();

});

// Handle errors when trying to download the image.
request.on('error', function(err){

    // Some error handling here...

    // Send out an error.
    return res.json(500, file);

});

// Perform the request.
request.perform();

```

I don't get any other errors than the seg fault.

Forgot to mention, that instance is running on Mac OS X.

**Comment by jiangmiao** [comment]
Is there the segment fault in examples/low-level.js too?

**Comment by jValdron** [comment]
No seg fault in low-level.js, however, after everything is done, I get: "Bus error: 10"

**Comment by jiangmiao** [comment]
It's too weird, near nothing changed in node-curl.h, the possible thing is the optimize level, but I've changed -O2 to -O1 because of issue #6 and #14

**Comment by jiangmiao** [comment]
I found the reason, I release the persistent handle in the end which after on_end and on_error called, v8 seems still need the handle to do something though they are the last function.
Now the issue should be fixed.

**Comment by jiangmiao** [comment]
another hint, curl.close() should be called in event 'error' too.

**Comment by jValdron** [comment]
Thanks, added the `curl.close()` in the error event. Also upgraded to 0.2.2, still getting a Segmentation fault 11

**Comment by jiangmiao** [comment]
Have you tried v0.2.1? I removed reference in 0.2.1 but add back to 0.2.2, because I run the code 1 hour to get localhost file with 5000 parallel and didn't get any error.

**Comment by jValdron** [comment]
Same with 0.2.1 unfortunately

**Comment by jValdron** [comment]
Hey, just to let you know, I made it work just fine now. Just had a few lines missing. Was using the old version for a while, but just upgraded today.

**Comment by jiangmiao** [comment]
Nice, Thanks for feedback.
